apiVersion: v1  # Specifies the API version for the Service resource, which is v1.
kind: Service   # The kind of resource being defined here is a Service.
metadata:
  name: products-db  # The name of the Service is products-db.
  labels:
    kubernetes.courselabs.co: hackathon  # Custom label for organizing resources related to the hackathon project.
    app: widgetario  # Label indicating that this Service is part of the widgetario application.
spec:
  ports:
    - port: 5432  # The Service exposes port 5432, which is the default port for PostgreSQL.
      targetPort: postgres  # The traffic coming to port 5432 will be forwarded to the "postgres" port in the Pods.
  selector:
    app: widgetario  # This Service selects Pods with the label app: widgetario.
    component: products-db  # This Service specifically selects Pods with the label component: products-db.
  type: ClusterIP  # The Service is of type ClusterIP, meaning it is only accessible from within the cluster.
