apiVersion: v1  # Specifies the API version for the Secret resource, which is v1.
kind: Secret    # The kind of resource being defined is a Secret. Secrets store sensitive data.
metadata:
  name: products-db-password  # The name of the Secret is 'products-db-password', which is used by the products-db Deployment.
  labels:
    kubernetes.courselabs.co: hackathon  # Custom label for organizing resources related to the hackathon project.
type: Opaque   # The Secret type is 'Opaque', which is used to store arbitrary user-defined data.
stringData:
  POSTGRES_PASSWORD: h4ckkath0n  # The actual data in the Secret. Here, the 'POSTGRES_PASSWORD' key is set to 'h4ckkath0n'.
