apiVersion: apps/v1  # Specifies the API version for the Deployment resource, which is apps/v1.
kind: Deployment     # The kind of resource being defined here is a Deployment.
metadata:
  name: web          # The name of the Deployment is web.
  labels:
    app: widgetario  # Label indicating that this Deployment is part of the widgetario application.
    kubernetes.courselabs.co: hackathon  # Custom label for grouping resources related to a hackathon project.
spec:
  selector:
    matchLabels:  # Defines the labels that should be used to select the Pods controlled by this Deployment.
      app: widgetario  # Selects Pods with the label app: widgetario.
      component: web  # Selects Pods with the label component: web.
  template:  # The Pod template, which defines the configuration for the Pods created by this Deployment.
    metadata:
      labels:  # The labels applied to the Pods created by this Deployment.
        app: widgetario  # Labels the Pods as part of the widgetario application.
        component: web  # Labels the Pods as part of the web component.
        hackathon: part-1  # Custom label indicating that these Pods are part of the first part of the hackathon.
    spec:
      containers:
        - name: app  # The name of the container inside the Pod.
          image: widgetario/web:21.03  # The Docker image used for this container (web service version 21.03).
          ports:
            - containerPort: 80  # The container exposes port 80 (typically used for HTTP traffic).
              name: http  # The port is named "http" for clarity in networking configurations.
