apiVersion: v1  # Specifies the API version for the Service resource, which is v1.
kind: Service   # The kind of resource being defined here is a Service.
metadata:
  name: stock-api  # The name of the Service is stock-api.
  labels:
    kubernetes.courselabs.co: hackathon  # Custom label for grouping resources related to a hackathon project.
    app: widgetario  # Label indicating that this Service is part of the widgetario application.
spec:
  ports:
    - port: 8080  # The Service will expose port 8080 for external or internal traffic.
      targetPort: http  # Traffic on port 8080 will be forwarded to the "http" port in the Pods.
  selector:
    app: widgetario  # This Service will select Pods with the label app: widgetario.
    component: stock-api  # This Service will specifically select Pods with the label component: stock-api.
  type: ClusterIP  # The Service is of type ClusterIP, meaning it is only accessible within the Kubernetes cluster.
