apiVersion: v1  # Specifies the API version for the Service resource, which is v1.
kind: Service   # The kind of resource being defined here is a Service.
metadata:
  name: products-api  # The name of the Service is products-api.
  labels:
    kubernetes.courselabs.co: hackathon  # Custom label for grouping resources related to a hackathon project.
    app: widgetario  # Label indicating that this Service is part of the widgetario application.
spec:
  ports:
    - port: 80  # The Service exposes port 80 for external or internal traffic.
      targetPort: http  # Traffic on port 80 will be forwarded to the "http" port in the Pods.
  selector:
    app: widgetario  # This Service will select Pods with the label app: widgetario.
    component: products-api  # This Service will specifically select Pods with the label component: products-api.
  type: ClusterIP  # The Service is of type ClusterIP, meaning it is only accessible from within the cluster.
