apiVersion: v1  # Specifies the API version for the Secret resource, which is v1.
kind: Secret    # The kind of resource being defined here is a Secret.
metadata:
  name: products-api-db  # The name of the Secret is products-api-db.
  labels:
    kubernetes.courselabs.co: hackathon  # Custom label for organizing resources related to the hackathon project.
type: Opaque  # The type of the Secret is Opaque, meaning it stores arbitrary user-defined data (like credentials or configuration).
stringData:
  application.properties: |-
    spring.jpa.database=POSTGRESQL  # Specifies the database type (PostgreSQL).
    spring.datasource.platform=postgres  # Specifies the platform for the datasource (PostgreSQL).
    spring.datasource.url=jdbc:postgresql://products-db:5432/postgres  # The JDBC URL for connecting to the PostgreSQL database (using the `products-db` service).
    spring.datasource.username=postgres  # The username used for connecting to the database.
    spring.datasource.password=h4ckkath0n  # The password used for connecting to the database.
