apiVersion: apps/v1  # Specifies the API version for the Deployment resource, which is apps/v1.
kind: Deployment    # The kind of resource being defined is a Deployment. A Deployment manages the deployment of Pods.
metadata:
  name: web  # The name of the Deployment is 'web'. This is used to identify and manage the Deployment.
  labels:
    kubernetes.courselabs.co: hackathon  # Custom label to categorize resources related to the hackathon project.
    app: widgetario  # Label indicating that this Deployment is for the widgetario application.
spec:
  selector:
    matchLabels:
        app: widgetario  # Selector that matches Pods with the label 'app: widgetario'.
        component: web  # Selector that matches Pods with the label 'component: web'.
  template:
    metadata:
      labels:
        app: widgetario  # Label applied to the Pods created by this Deployment.
        component: web  # Label indicating that these Pods belong to the 'web' component.
        hackathon: part-1  # Custom label for organizing Pods related to 'part-1' of the hackathon.
    spec:
      containers:
        - name: app  # The name of the container within the Pod.
          image: widgetario/web:21.03  # The Docker image to use for the container.
          ports:
            - containerPort: 80  # Port exposed by the container (the web service will be available on this port).
              name: http  # The name of the port, which is 'http' in this case.
          envFrom:
            - configMapRef:
                name: web-features  # References the 'web-features' ConfigMap to inject environment variables into the container.
          volumeMounts:
            - name: api-config  # Name of the volume to mount.
              mountPath: "/app/secrets"  # The directory inside the container where the volume will be mounted.
              readOnly: true  # The volume is mounted as read-only inside the container.
      volumes:
        - name: api-config  # The name of the volume that will be used in the container.
          secret:
            secretName: web-api  # The volume uses a Kubernetes Secret named 'web-api' to populate its contents.
