apiVersion: v1  # Specifies the API version for the Secret resource, which is v1.
kind: Secret    # The kind of resource being defined is a Secret. Secrets are used to store sensitive data, like credentials or API keys.
metadata:
  name: web-api  # The name of the Secret is 'web-api', which can be referenced by other resources like Pods or Deployments.
  labels:
    kubernetes.courselabs.co: hackathon  # Custom label to categorize this Secret for the hackathon project.
type: Opaque  # The type of Secret is 'Opaque', which means it stores arbitrary data, not tied to any specific type (e.g., Docker credentials, SSH keys, etc.).
stringData:
  api.json: |-  # 'stringData' allows you to define the Secret's data as plain text. The key here is 'api.json', which will hold the configuration.
    {
      "Widgetario": {
        "ProductsApi": {
          "Url": "http://products-api.default.svc.cluster.local/products"  # URL for the Products API service in Kubernetes.
        },
        "StockApi": {
          "Url": "http://stock-api.default.svc.cluster.local/stock"  # URL for the Stock API service in Kubernetes.
        }
      }
    }
