apiVersion: v1  # Specifies the API version for the Secret resource, which is v1.
kind: Secret    # The kind of resource being defined is a Secret. Secrets store sensitive data.
metadata:
  name: stock-api-connection  # The name of the Secret is 'stock-api-connection', which will be referenced by the 'stock-api' Deployment.
  labels:
    kubernetes.courselabs.co: hackathon  # Custom label for organizing resources related to the hackathon project.
type: Opaque   # The Secret type is 'Opaque', which is used to store arbitrary user-defined data.
stringData:
  POSTGRES_CONNECTION_STRING: "host=products-db port=5432 user=postgres password=h4ckkath0n dbname=postgres sslmode=disable"  # The actual connection string for PostgreSQL.
