apiVersion: v1  # Specifies the API version for the Service resource, which is v1.
kind: Service   # The kind of resource being defined is a Service. Services expose applications running on a set of Pods.
metadata:
  name: stock-api  # The name of the Service is 'stock-api', which represents the service for the stock API.
  labels:
    kubernetes.courselabs.co: hackathon  # A custom label used to categorize resources related to the hackathon project.
    app: widgetario  # A label indicating that this Service is part of the widgetario application.
spec:
  ports:
    - port: 80  # The port on the Service that clients can access to reach the application (the stock API).
      targetPort: http  # The port on the container to which the Service forwards traffic (the container exposes 'http' port).
  selector:
    app: widgetario  # The Service selects Pods with the label 'app: widgetario'.
    component: stock-api  # The Service specifically targets Pods labeled with 'component: stock-api'.
  type: ClusterIP  # The type of the Service is 'ClusterIP', which means it is only accessible within the Kubernetes cluster.
