apiVersion: v1  # Specifies the API version for the Service resource.
kind: Service  # This is a Kubernetes Service resource, which exposes Pods to external or internal traffic.
metadata:
  name: products-api  # The name of the Service.
  labels:
    kubernetes.courselabs.co: hackathon  # Custom label for grouping resources related to a hackathon project.
    app: widgetario  # Label indicating that this Service is part of the widgetario application.
spec:
  ports:
    - port: 80  # The Service will expose port 80 for external traffic.
      targetPort: http  # The traffic on port 80 will be forwarded to the "http" port in the container.
  selector:
    app: widgetario  # This Service targets Pods with the label app: widgetario.
    component: products-api  # This Service targets Pods with the label component: products-api.
  type: ClusterIP  # The Service is of type ClusterIP, meaning it is only accessible within the Kubernetes cluster.
